# -*- coding: utf-8 -*-
"""LinAlg_Lab8_Arcera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ya1SZ8u5TnL57-aKPJsfcxEnnErSxCWO

# **Arcera, Edhnaer**
## Laboratory 8 : System of Linear Equations

### **Exercise**

1. Try to find your own example of a system of linear equations (minimum of 2 equations) and solve them using the inverse equation. Explain the details of your example.
2. Using your example in (1) solve it using `np.linalg.solve()`. Explain the function and its difference using the inverse equation.


$Let : 
t = \text{Toblerone}, h = \text{Hersheys}, k = \text{Kisses} \\ \\ $

### *Exercise 1*
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

"""$$\begin{bmatrix}40&20&10\\35&50&20\\50&40&30\end{bmatrix}\cdot\begin{bmatrix}t\\h\\k\end{bmatrix} = \begin{bmatrix}5,380\\7,475\\9,110\end{bmatrix}$$
So following our formula in solving linear equation $X r = Y$ we can solve for $t, h$ and $k$.

$Let : \\ 
t = \text{toblerone}, h = \text{hersheys}, k = \text{kisses} \\ \\ $
"""

chocolates = np.array([
    [40, 20, 10],
    [35, 50, 20],
    [50, 40, 30]
])
cost = np.array([
    [5380],
    [7475],
    [9110]
])
pricesE = np.linalg.inv(chocolates) @ cost
pricesA = np.linalg.solve(chocolates,price)
###########################################################################
print("Answer using linalg.inv")
print('The price of one toblerone is: PHP {:.2f}'.format(float(prices[0])))
print('The price of one hersheys is: PHP {:.2f}'.format(float(prices[1])))
print('The price of one pack of kisses is: PHP {:.2f}'.format(float(prices[2])))

print("************************************************************ ")

print("Answer using linalg.solve")
print('The price of one toblerone is: PHP {:.2f}'.format(float(prices[0])))
print('The price of one hersheys is: PHP {:.2f}'.format(float(prices[1])))
print('The price of one pack of kisses is: PHP {:.2f}'.format(float(prices[2])))